POST http://localhost:8080/api/v1/raycluster
Content-Type: application/json

{
  "clusterType": "ray",
  "clusterName": "raycluster-kuberay",
  "namespace": "chess-kuberay",
  "machines": [
    {
      "machineType": "single",
      "name": "ray-head",
      "cpu": "2",
      "memory": "4Gi",
      "customResources": {
        "nvidia.com/gpu": "1"
      },
      "ports": [
        {
          "name": "gcs-server",
          "containerPort": 6379
        },
        {
          "name": "dashboard",
          "containerPort": 8265
        },
        {
          "name": "client",
          "containerPort": 10001
        }
      ],
      "isHeadNode": true
    },
    {
      "machineType": "group",
      "name": "ray-worker",
      "cpu": "2",
      "memory": "4Gi",
      "ports": [
        {
          "name": "port-test",
          "containerPort": 8081
        }
      ],
      "groupName": "workergroup",
      "replicas": 2,
      "minReplicas": 2,
      "maxReplicas": 3
    }
  ]
}