POST http://localhost:8080/api/v1/rayjob
Content-Type: application/json

{
  "job": {
    "name": "deepseek-r1-671b",
    "cmd": "vllm serve /mnt/data/models/DeepSeek-R1   --tensor-parallel-size 8    --pipeline-parallel-size 6   --swap-space 32   --trust-remote-code"
  },
  "namespace": "idp-kuberay",
  "machines": [
    {
      "machineType": "single",
      "name": "ray-head",
      "cpu": "32",
      "memory": "512Gi",
      "customResources": {
        "nvidia.com/gpu": "10"
      },
      "volumes": [
        {
          "name": "volume-deepseek-r1",
          "source": "nfs-pvc-model-deepseek-r1-671b",
          "path": "/mnt/data/models/DeepSeek-R1"
        },
        {
          "name": "volume-runcode-deepseek-r1-671b",
          "path": "/home/ray/runcode",
          "configMap": {
            "name": "runcode-deepseek-r1-671b",
            "items": [
              {
                "key": "vllm_deepseek_r1_671b.py",
                "path": "vllm_deepseek_r1_671b.py"
              }
            ]
          }
        }
      ],
      "ports": [
        {
          "name": "gcs-server",
          "containerPort": 6379
        },
        {
          "name": "dashboard",
          "containerPort": 8265
        },
        {
          "name": "client",
          "containerPort": 10001
        }
      ],
      "isHeadNode": true
    },
    {
      "machineType": "group",
      "name": "ray-worker",
      "cpu": "32",
      "memory": "512Gi",
      "customResources": {
        "nvidia.com/gpu": "10"
      },
      "volumes": [
        {
          "name": "volume-deepseek-r1",
          "source": "nfs-pvc-model-deepseek-r1-671b",
          "path": "/mnt/data/models/DeepSeek-R1"
        }
      ],
      "groupName": "workergroup",
      "replicas": 3,
      "minReplicas": 3,
      "maxReplicas": 3
    }
  ]
}