apiVersion: v1
kind: Service
metadata:
  name: deepseek-r1-671b-raycluster-target-svc
  namespace: kuberay
  labels:
    app.kubernetes.io/created-by: kuberay-operator
    app.kubernetes.io/name: kuberay
    ray.io/cluster: deepseek-r1-671b-raycluster-t4ld9
    ray.io/identifier: deepseek-r1-671b-raycluster-t4ld9-head
spec:
  type: NodePort
  ports:
  - name: target-port
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    app.kubernetes.io/created-by: kuberay-operator
    app.kubernetes.io/name: kuberay
    ray.io/cluster: deepseek-r1-671b-raycluster-t4ld9
    ray.io/identifier: deepseek-r1-671b-raycluster-t4ld9-head
    ray.io/node-type: head
  publishNotReadyAddresses: true