// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: podexec.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodExecService_Exec_FullMethodName = "/proto.PodExecService/Exec"
)

// PodExecServiceClient is the client API for PodExecService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Pod 终端执行服务
type PodExecServiceClient interface {
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecMessage, ExecMessage], error)
}

type podExecServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodExecServiceClient(cc grpc.ClientConnInterface) PodExecServiceClient {
	return &podExecServiceClient{cc}
}

func (c *podExecServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecMessage, ExecMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PodExecService_ServiceDesc.Streams[0], PodExecService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecMessage, ExecMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PodExecService_ExecClient = grpc.BidiStreamingClient[ExecMessage, ExecMessage]

// PodExecServiceServer is the server API for PodExecService service.
// All implementations must embed UnimplementedPodExecServiceServer
// for forward compatibility.
//
// Pod 终端执行服务
type PodExecServiceServer interface {
	Exec(grpc.BidiStreamingServer[ExecMessage, ExecMessage]) error
	mustEmbedUnimplementedPodExecServiceServer()
}

// UnimplementedPodExecServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodExecServiceServer struct{}

func (UnimplementedPodExecServiceServer) Exec(grpc.BidiStreamingServer[ExecMessage, ExecMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedPodExecServiceServer) mustEmbedUnimplementedPodExecServiceServer() {}
func (UnimplementedPodExecServiceServer) testEmbeddedByValue()                        {}

// UnsafePodExecServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodExecServiceServer will
// result in compilation errors.
type UnsafePodExecServiceServer interface {
	mustEmbedUnimplementedPodExecServiceServer()
}

func RegisterPodExecServiceServer(s grpc.ServiceRegistrar, srv PodExecServiceServer) {
	// If the following call pancis, it indicates UnimplementedPodExecServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodExecService_ServiceDesc, srv)
}

func _PodExecService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PodExecServiceServer).Exec(&grpc.GenericServerStream[ExecMessage, ExecMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PodExecService_ExecServer = grpc.BidiStreamingServer[ExecMessage, ExecMessage]

// PodExecService_ServiceDesc is the grpc.ServiceDesc for PodExecService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodExecService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PodExecService",
	HandlerType: (*PodExecServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _PodExecService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "podexec.proto",
}
