// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.12.4
// source: podlog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName   string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Container string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	// 是否跟随日志
	Follow bool `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	// 是否包含前缀时间戳
	Timestamps bool `protobuf:"varint,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	// 起始时间，RFC3339 格式字符串（可选）
	SinceTime string `protobuf:"bytes,6,opt,name=since_time,json=sinceTime,proto3" json:"since_time,omitempty"`
	// 最近 N 行（可选）
	TailLines int64 `protobuf:"varint,7,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// 是否包含前缀时间戳（可选）
	Previous      bool `protobuf:"varint,8,opt,name=previous,proto3" json:"previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_podlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_podlog_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LogRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *LogRequest) GetSinceTime() string {
	if x != nil {
		return x.SinceTime
	}
	return ""
}

func (x *LogRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogRequest) GetPrevious() bool {
	if x != nil {
		return x.Previous
	}
	return false
}

type LogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Log:
	//
	//	*LogResponse_Content
	//	*LogResponse_Error
	//	*LogResponse_Eof
	Log           isLogResponse_Log `protobuf_oneof:"log"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_podlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_podlog_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetLog() isLogResponse_Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *LogResponse) GetContent() []byte {
	if x != nil {
		if x, ok := x.Log.(*LogResponse_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *LogResponse) GetError() string {
	if x != nil {
		if x, ok := x.Log.(*LogResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *LogResponse) GetEof() bool {
	if x != nil {
		if x, ok := x.Log.(*LogResponse_Eof); ok {
			return x.Eof
		}
	}
	return false
}

type isLogResponse_Log interface {
	isLogResponse_Log()
}

type LogResponse_Content struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3,oneof"` // 日志内容
}

type LogResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // 错误消息（可选）
}

type LogResponse_Eof struct {
	Eof bool `protobuf:"varint,3,opt,name=eof,proto3,oneof"` // 是否结束（可选）
}

func (*LogResponse_Content) isLogResponse_Log() {}

func (*LogResponse_Error) isLogResponse_Log() {}

func (*LogResponse_Eof) isLogResponse_Log() {}

var File_podlog_proto protoreflect.FileDescriptor

var file_podlog_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x64, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x6e, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x22, 0x5c, 0x0a,
	0x0b, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x03, 0x65, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x03, 0x65, 0x6f, 0x66, 0x42, 0x05, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x32, 0x45, 0x0a, 0x0d, 0x50,
	0x6f, 0x64, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_podlog_proto_rawDescOnce sync.Once
	file_podlog_proto_rawDescData []byte
)

func file_podlog_proto_rawDescGZIP() []byte {
	file_podlog_proto_rawDescOnce.Do(func() {
		file_podlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podlog_proto_rawDesc), len(file_podlog_proto_rawDesc)))
	})
	return file_podlog_proto_rawDescData
}

var file_podlog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podlog_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: proto.LogRequest
	(*LogResponse)(nil), // 1: proto.LogResponse
}
var file_podlog_proto_depIdxs = []int32{
	0, // 0: proto.PodLogService.GetLogs:input_type -> proto.LogRequest
	1, // 1: proto.PodLogService.GetLogs:output_type -> proto.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podlog_proto_init() }
func file_podlog_proto_init() {
	if File_podlog_proto != nil {
		return
	}
	file_podlog_proto_msgTypes[1].OneofWrappers = []any{
		(*LogResponse_Content)(nil),
		(*LogResponse_Error)(nil),
		(*LogResponse_Eof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podlog_proto_rawDesc), len(file_podlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podlog_proto_goTypes,
		DependencyIndexes: file_podlog_proto_depIdxs,
		MessageInfos:      file_podlog_proto_msgTypes,
	}.Build()
	File_podlog_proto = out.File
	file_podlog_proto_goTypes = nil
	file_podlog_proto_depIdxs = nil
}
