// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: podlog.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodLogService_GetLogs_FullMethodName = "/proto.PodLogService/GetLogs"
)

// PodLogServiceClient is the client API for PodLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodLogServiceClient interface {
	// Establishes a server-side streaming connection to stream logs
	GetLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error)
}

type podLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodLogServiceClient(cc grpc.ClientConnInterface) PodLogServiceClient {
	return &podLogServiceClient{cc}
}

func (c *podLogServiceClient) GetLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PodLogService_ServiceDesc.Streams[0], PodLogService_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PodLogService_GetLogsClient = grpc.ServerStreamingClient[LogResponse]

// PodLogServiceServer is the server API for PodLogService service.
// All implementations must embed UnimplementedPodLogServiceServer
// for forward compatibility.
type PodLogServiceServer interface {
	// Establishes a server-side streaming connection to stream logs
	GetLogs(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error
	mustEmbedUnimplementedPodLogServiceServer()
}

// UnimplementedPodLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodLogServiceServer struct{}

func (UnimplementedPodLogServiceServer) GetLogs(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedPodLogServiceServer) mustEmbedUnimplementedPodLogServiceServer() {}
func (UnimplementedPodLogServiceServer) testEmbeddedByValue()                       {}

// UnsafePodLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodLogServiceServer will
// result in compilation errors.
type UnsafePodLogServiceServer interface {
	mustEmbedUnimplementedPodLogServiceServer()
}

func RegisterPodLogServiceServer(s grpc.ServiceRegistrar, srv PodLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedPodLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodLogService_ServiceDesc, srv)
}

func _PodLogService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PodLogServiceServer).GetLogs(m, &grpc.GenericServerStream[LogRequest, LogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PodLogService_GetLogsServer = grpc.ServerStreamingServer[LogResponse]

// PodLogService_ServiceDesc is the grpc.ServiceDesc for PodLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PodLogService",
	HandlerType: (*PodLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _PodLogService_GetLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "podlog.proto",
}
